### ISSUE TITLE
How to configure vue-toastify for Nuxt?

### ISSUE THREAD

**Issue by claytongf** [nandi95/vue-toastify#20]
I'm trying to use it in Nuxt but I receive an error after adding it to plugins.
config in nuxt.config.js:
`plugins: [
    '~plugins/vtoastify.js'
  ],`
setting up in plugins/vtoastify.js:

`import Vue from 'vue'
import VueToastify from 'vue-toastify'

Vue.use(VueToastify)`

after that, I receive an error in browser:

ReferenceError
window is not defined

in console:
Uncaught InternalError: too much recursion

And shows an error in import VueToastify

module "/nuxtproject/node_modules/vue-toastify/dist/vue-toastify.umd.min"
Could not find a declaration file for module 'vue-toastify'. '/nuxtproject/node_modules/vue-toastify/dist/vue-toastify.umd.min.js' implicitly has an 'any' type.
  Try `npm install @types/vue-toastify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-toastify';`ts(7016)

But the file vue-toastify.umd.min.js exists on that folder.
Any ideas how to setup vue-toastify on Nuxt?

Note: I'm not using typescript

**Comment by LuisRego** [comment]
I'm having the same issue.

**Comment by nandi95** [comment]
Do you have an example repo @claytongf ?
I was able to set it up following the [nuxt docs](https://nuxtjs.org/guide/plugins/#vue-plugins)

in this case it was:
```js
// plugins/vue-toastify.js

import Vue from "vue";
import VueToastify from "vue-toastify";

Vue.use(VueToastify);
```

```js
// nuxt.config.js
...
plugins: ["@/plugins/vue-toastify.js"]
...
```

and in a component: 
```js
mounted() {
  this.$vToastify.success('it worked');
},
```

Regardless it would be a good idea to add support for nuxt so this won't be happening in the future.

Can I close this or is this still an issue?

**Comment by claytongf** [comment]
Hi,
I've created an empty nuxt project installing vue-toastify as described in the nuxt documentation.
https://github.com/claytongf/vue-toastify-test
I still get the error
https://ibb.co/k6MgYkZ
I've sent a screenshot of the error.

**Comment by nandi95** [comment]
Try updating the plugins array to this:
```js
plugins: [
    // https://stackoverflow.com/a/58633076/11672649
    { src: '@/plugins/vue-toastify.js', mode: 'client' }
],
```

In the config your target is set to `"server"`

**Comment by nandi95** [comment]
@claytongf see above
