### ISSUE TITLE
Major rewrite with vue 3 + typescript

### ISSUE THREAD

**Issue by nandi95** [nandi95/vue-toastify#24]
I'm planning a major rebuild of the package with typescript and vue 3.
composition api will allow for much cleaner code. I excpect slight differences in the api from the current one but nothing too painful to upgrade.
With this rebuild I will aim for 100 test coverage and better documentation and demo site.

**Comment by xlcrr** [comment]
hey, any news on this for vue 3? I love this package and use it everywhere!

**Comment by nandi95** [comment]
I have a branch going where I started the work, but it has not been a priority due to work and life.
It is good to know there is an interest though and I will try to spend some time on this when I can.

**Comment by thecrypticshadow** [comment]
Same also looking to use this with Vue 3.

**Comment by markosole** [comment]
Hi @nandi95, thanks for good looking and useful plugin. Are there any updates for VUE 3 support?

**Comment by nandi95** [comment]
> Hi @nandi95, thanks for good looking and useful plugin. Are there any updates for VUE 3 support?

Hi @markosole 
It's a slow progress, you can see the latest changes I made was last week https://github.com/nandi95/vue-toastify/pull/34/commits/c7bc53ec1cecdcfde0cd88e41d12c7edc9273a4f

**Comment by nandi95** [comment]
Testing coverage plan now scrapped to release quicker.
Hopefully testing will come later 🤞

**Comment by nandi95** [comment]
vue 3 support is now available under the tag 2.0.0-alpha.1
```shell
npm i vue-toastify@2.0.0-alpha.1
```
[documentation is still in progress](https://github.com/nandi95/vue-toastify/pull/34/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1), but the jsdoc/typescript should show the documentation and give an idea of the types.
I'll keep this issue open until the PR is merged.
