### ISSUE TITLE
Can I use it inside a method?

### ISSUE THREAD

**Issue by marufmax** [nandi95/vue-toastify#3]
Hi, Thanks for this library. 

Can I use it without `<vue-toastify :your-props="here"></vue-toastify>`  this component? 

I want to show notification inside a method and I don't want to mess around with template. 

like simply: `this.$toastify.success('Weird success text');`

something like this?

**Comment by nandi95** [comment]
You have to include the component but you don't have to pass the props. This is currently a single component not a plugin.

**Comment by nandi95** [comment]
@marufmax This is a great idea, I'll make sure to add this when moving to release 1.0
