### ISSUE TITLE
Custom styles object?

### ISSUE THREAD

**Issue by xlcrr** [nandi95/vue-toastify#4]
Hi, cool plugin. Thanks for this.

Is it possible to pass custom styles, or override the default styling? In particular, background colour, text colour, font-size.

Accepting a styles object would be a nice touch.

Many thanks

**Comment by nandi95** [comment]
Not at the moment.

I'll extract the styles when releasing 1.0 into a separate style-sheets for the light and dark theme and add documentation for what class controls what element.

**Comment by xlcrr** [comment]
That would be great thanks !

I would love to see the ability to pass a styles object to control background color, font family, etc

Keep up the good work <3

**Comment by nandi95** [comment]
Is that because you would want to change the background colour while it is being displayed?
What's the benefit of passing it through JS?
@xlcrr

**Comment by nandi95** [comment]
Version 1.0.0 now includes option to customize styles.
